name: ros-ghc-8.6-cabal-2.4

# Trigger the workflow on push or pull request
on:
  - pull_request
  - push

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        cabal: ["3.12"]
        ghc:
          - "9.10"

    steps:

    - uses: haskell-actions/setup@main
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Prepare environment
      run: |
        echo "$HOME/.ghcup/bin" >> $GITHUB_PATH
        echo "$HOME/.cabal/bin" >> $GITHUB_PATH
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        cabal install --lib copilot copilot-c99 copilot-language copilot-theorem \
          copilot-libraries copilot-interpreter

    - name: Install ogma
      run: |
        cabal install ogma-cli:ogma

    - name: Generate ROS app
      run: |
        ogma ros --app-target-dir demo --variable-db ogma-cli/examples/ros-copilot/vars-db --variable-file ogma-cli/examples/ros-copilot/variables --handlers-file ogma-cli/examples/ros-copilot/handlers
        runhaskell ROS.hs
        find demo/
        cd demo/
        docker build .
